//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacanteEmpresa
    {
        public int IdVacanteEmpresa { get; set; }
        public Nullable<int> IdVacante { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Vacante Vacante { get; set; }
    }
}
