//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacante()
        {
            this.CandidatoVacante = new HashSet<CandidatoVacante>();
            this.VacanteEmpresa = new HashSet<VacanteEmpresa>();
        }
    
        public int IdVacante { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public string UrlVacante { get; set; }
        public byte IdEstatusVacante { get; set; }
    
        public virtual EstatusVacante EstatusVacante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatoVacante> CandidatoVacante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacanteEmpresa> VacanteEmpresa { get; set; }
    }
}
